### ISSUE TITLE
TypeError: DLT.TransformStream is not a constructor.

### ISSUE THREAD

**Issue by Marucik** [esrlabs/dlt-reader#1]
After building project, I get error message as in title: `TypeError: DLT.TransformStream is not a constructor`.

Is it problem with building or something is missing in source files?

**Comment by Marucik** [comment]
Error due to old Node version.

**Comment by DmitryAstafyev** [comment]
> Error due to old Node version.

In any way, I've updated all npm-dependencies. It was quite outdated already.
